import {ArrowDown,ArrowUpRight,BrainCircuit,Code2,CloudCog,Workflow,Sparkles,ShieldCheck} from 'lucide-react';import {Link} from 'react-router-dom';import {site,projects,services} from '../data/site';import {SectionHeader} from '../components/Section';import {ProjectCard} from '../components/ProjectCard';import {Architecture} from '../components/Architecture'
import {PortfolioAssistant} from '../components/PortfolioAssistant'
import {ResponsiveImage} from '../components/ResponsiveImage'
export function Home(){return <>
<section className="hero"><div className="hero-glow"></div><div className="container hero-grid"><div className="hero-copy"><div className="availability"><span className="pulse"></span>{site.availability}</div><p className="eyebrow">WEB DEVELOPMENT · AI INTEGRATION · AUTOMATION</p><h1>Web Developer & Software Engineer <span className="text-gradient">building useful</span> digital solutions.</h1><p className="hero-lead">I build responsive web applications, connect interfaces to APIs and third-party services, automate digital workflows, and apply AI where it adds practical value.</p><div className="hero-actions"><Link to="/contact" className="button">Hire Me <ArrowUpRight size={17}/></Link><Link to="/projects" className="button button-ghost">View My Work <ArrowDown size={16}/></Link><a href={site.cv} className="text-link">Download CV <ArrowUpRight size={15}/></a></div><div className="hero-proof"><span>React.js</span><span>AI Integration</span><span>APIs</span><span>Automation</span><span>AI-Assisted Development</span></div></div><div className="hero-media"><div className="portrait-frame"><ResponsiveImage avif={site.heroImage.avif} webp={site.heroImage.webp} fallback={site.heroImage.fallback} alt="George Owulama Andzutsi working at a computer in a professional software engineering environment" loading="eager" fetchPriority="high"/><div className="portrait-caption"><span>GEORGE OWULAMA ANDZUTSI</span><span>AI / SOFTWARE ENGINEER</span></div></div><div className="floating-code"><span>01</span><code>AI + Engineering</code><small>make intelligence useful</small></div></div></div></section>
<section className="strip"><div className="container strip-grid">{[['React.js',Code2],['TypeScript',Code2],['API Integration',BrainCircuit],['Automation',Workflow],['AI Integration',Sparkles],['Deployment',CloudCog]].map(([t,I])=><div className="strip-item" key={t as string}>{<I size={17}/>}<span>{t as string}</span></div>)}</div></section>
<section className="section"><div className="container two-col"><div><p className="eyebrow">THE DIFFERENCE</p><h2>AI is powerful. <span className="text-gradient">Engineering makes it useful.</span></h2></div><div><p className="lead">Effective AI products need more than a model call. They need architecture, APIs, data, authentication, automation, security, user experience and deployment.</p><Link className="text-link" to="/about">Read My Story <ArrowUpRight size={15}/></Link></div></div></section>
<section className="section section-alt"><div className="container"><SectionHeader eyebrow="SELECTED WORK" title="Projects built around real engineering problems." description="A curated set of verified projects and engineering references, with live links and project status labeled honestly." link={{label:'View all projects',to:'/projects'}}/><div className="project-grid">{projects.slice(0,4).map(p=><ProjectCard key={p.slug} project={p}/>)}</div></div></section>
<section className="section"><div className="container"><SectionHeader eyebrow="FROM IDEA TO DEPLOYMENT" title="A complete engineering lifecycle." description="A practical process for moving from an ambiguous problem to a maintainable deployed system."/><div className="process-grid">{['Discover','Architect','Build','Integrate AI','Secure','Test','Deploy','Improve'].map((x,i)=><div className="process-step" key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></div>)}</div></div></section>
<section className="section section-dark"><div className="container two-col architecture-wrap"><div><p className="eyebrow">SYSTEM THINKING</p><h2>Software architecture that makes the AI layer <span className="text-gradient">work in context.</span></h2><p className="lead">From the user interface to APIs, business logic, model providers and data, the system has to work as one dependable product.</p></div><Architecture/></div></section>
<section className="section"><div className="container"><SectionHeader eyebrow="WHAT I CAN BUILD" title="Technology shaped around useful outcomes."/><div className="capability-grid">{services.map((s,i)=><div className="capability" key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.description}</p><Link to="/services" className="text-link">Explore <ArrowUpRight size={14}/></Link></div>)}</div></div></section>
<PortfolioAssistant/>
<section className="section cta-section"><div className="container cta-box"><div><p className="eyebrow">LET'S TALK</p><h2>Have a problem worth solving?</h2><p className="lead">Tell me what you are building, where you are stuck, or what you want to automate.</p></div><Link className="button" to="/start-a-project">Start a Project <ArrowUpRight size={17}/></Link></div></section>
</>}
