import type {ReactNode} from 'react'
import {GitBranch,Bot,CreditCard,Video,Workflow,Code2,Database,Zap,FileText,HeartPulse} from 'lucide-react'
const themes:Record<string,{label:string;accent:string;secondary:string}>={georgepay:{label:'GEORGEPAY',accent:'#38bdf8',secondary:'#6366f1'},'codeflow-ai':{label:'CODEFLOW',accent:'#22d3ee',secondary:'#3b82f6'},regismeet:{label:'REGISMEET',accent:'#a78bfa',secondary:'#6366f1'},'workflow-automation-api-integration':{label:'AUTOMATION',accent:'#34d399',secondary:'#06b6d4'},'verdant-foundation':{label:'VERDANT',accent:'#84cc16',secondary:'#15803d'},'ai-report-processing':{label:'AI REPORTS',accent:'#f59e0b',secondary:'#ea580c'}}
function Frame({children,className=''}:{children:ReactNode;className?:string}){return <div className={`cover-frame ${className}`}>{children}</div>}
export function ProjectCover2({slug,title}:{slug:string;title:string}){
 const theme=themes[slug]??{label:title.toUpperCase(),accent:'#38bdf8',secondary:'#6366f1'}
 if(slug==='georgepay')return <div className="project-cover" aria-label={`${title} project cover`}><div className="cover-orbit" style={{background:`radial-gradient(circle,${theme.accent}33,transparent 62%)`}}/><Frame><div className="cover-bar"><CreditCard size={15}/><span>{theme.label}</span><span className="cover-dot" style={{background:theme.accent}}/></div><div className="payment-layout"><div className="payment-card" style={{background:`linear-gradient(135deg,${theme.secondary},${theme.accent})`}}><span>GeorgePay</span><strong>•••• 4821</strong><small>PAYMENT WORKFLOW</small></div><div className="transaction-list"><i/><i/><i/><i/></div></div></Frame><div className="cover-caption"><span style={{color:theme.accent}}>PAYMENTS</span><b>Connect · Authenticate · Pay</b></div></div>
 if(slug==='codeflow-ai')return <div className="project-cover" aria-label={`${title} project cover`}><div className="cover-glow" style={{background:`radial-gradient(circle,${theme.accent}2e,transparent 60%)`}}/><Frame><div className="cover-bar"><Code2 size={15}/><span>{theme.label}</span><div className="window-dots"><i/><i/><i/></div></div><div className="code-layout"><div className="code-editor"><b>&lt;AIWorkspace /&gt;</b><span>const response = await</span><span>assistant.generate(prompt)</span><span>return response</span><em>● ● ● ● ●</em></div><div className="ai-panel"><Bot size={20}/><strong>AI Assistant</strong><small>Gemini + Groq fallback</small><div className="ai-line"/></div></div></Frame><div className="cover-caption"><span style={{color:theme.accent}}>AI CODE ASSISTANT</span><b>Build with intelligent tools</b></div></div>
 if(slug==='regismeet')return <div className="project-cover" aria-label={`${title} project cover`}><div className="cover-glow" style={{background:`radial-gradient(circle,${theme.accent}26,transparent 60%)`}}/><Frame><div className="cover-bar"><Video size={15}/><span>{theme.label}</span><span className="live-pill">BUILDING</span></div><div className="meeting-grid"><div/><div/><div/><div/></div><div className="meeting-controls"><span/><span/><span/><span/><b>End</b></div></Frame><div className="cover-caption"><span style={{color:theme.accent}}>MEETING APP</span><b>Connect · Collaborate · Meet</b></div></div>
 if(slug==='verdant-foundation')return <div className="project-cover" aria-label={`${title} project cover`}><div className="cover-glow" style={{background:`radial-gradient(circle,${theme.accent}26,transparent 60%)`}}/><Frame><div className="cover-bar"><HeartPulse size={15}/><span>{theme.label}</span><span className="cover-status">WEBSITE</span></div><div className="foundation-layout"><div className="foundation-hero"><strong>Verdant</strong><small>Foundation</small></div><div className="foundation-panel"><span>DONATE</span><b>Support the mission</b><i/></div></div></Frame><div className="cover-caption"><span style={{color:theme.accent}}>FOUNDATION WEBSITE</span><b>Inform · Engage · Support</b></div></div>
 if(slug==='ai-report-processing')return <div className="project-cover" aria-label={`${title} project cover`}><div className="cover-glow" style={{background:`radial-gradient(circle,${theme.accent}24,transparent 60%)`}}/><Frame><div className="cover-bar"><FileText size={15}/><span>{theme.label}</span><span className="cover-status">PROTOTYPE</span></div><div className="report-layout"><div className="report-doc"><i/><i/><i/><i/><i/></div><div className="report-ai"><Bot size={20}/><strong>Groq API</strong><small>Structured processing</small></div></div></Frame><div className="cover-caption"><span style={{color:theme.accent}}>AI PROTOTYPE</span><b>Process · Structure · Evaluate</b></div></div>
 return <div className="project-cover" aria-label={`${title} project cover`}><div className="cover-glow" style={{background:`radial-gradient(circle,${theme.accent}26,transparent 60%)`}}/><Frame><div className="cover-bar"><Workflow size={15}/><span>{theme.label}</span><span className="cover-status">AUTOMATED</span></div><div className="workflow-canvas"><div className="flow-node"><Zap size={15}/><span>Trigger</span></div><div className="flow-line"/><div className="flow-node"><GitBranch size={15}/><span>API</span></div><div className="flow-line"/><div className="flow-node"><Database size={15}/><span>Output</span></div></div><div className="workflow-footer"><span>Zapier</span><span>Make.com</span><span>Webhooks</span><span>JSON</span></div></Frame><div className="cover-caption"><span style={{color:theme.accent}}>API + WORKFLOW</span><b>Connect systems. Automate work.</b></div></div>
}
